import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../styles/globals.css";
import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    icons: [
        {rel: 'icon', url: '/img/logo.png', sizes: "32x32"}
    ],
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html suppressHydrationWarning={true} lang="en">
                <body className={inter.className}>
                <ToastContainer
                    position={'bottom-right'}
                    hideProgressBar={false}
                    closeOnClick
                    rtl={false}
                    theme={'light'}
                />
                {children}</body>
            </html>
        </>
    );
}
